name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Push clean commit to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Reset local git history inside the runner to only the latest state
          git checkout --orphan temp_branch
          git add -A
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git commit -m "Deploy clean app without binary history"
          git push --force https://Rudesh0796:$HF_TOKEN@huggingface.co/spaces/Rudesh0796/Groq-ChatBot-using-LLM temp_branch:main
